//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace Disty.Model.MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dept
    {
        public Dept()
        {
            this.Lists = new HashSet<List>();
        }
    
        public int Id { get; set; }
        [Index(IsUnique = true)]
        public string Name { get; set; }
    
        public virtual ICollection<List> Lists { get; set; }
    }
}
